#+TITLE: Thesis
#+AUTHOR: Bart van Pelt

# +OPTIONS: toc:nil
# +EXCLUDE_TAGS: questions

* Inleiding
Dit bestand bevat een overzicht van zaken die ik op papier wil zetten.

Als eerst een voorgestelde setup van mijn thesis.
Voorstel is om hem op te splitsen in twee delen, het AZO deel en het rho_c deel.

Gezien het AZO deel een vrij coherent verhaal is lijkt het me een slecht idee deze door midden te splitsen met een ellenlange "methods" sectie.
Hier ga ik kort in op de rho_c meting, iets met "a custom setup, detailed in Part II".
Ik rond het AZO verhaal meteen af, voordat ik naar de meetsetup ga.

Daarna volgt een verhaal over de contactweerstandssetup.
Voordeel van dit na het AZO verhaal doen is dat een deel van de theorie over contactweerstanden al aan bod is gekomen, en hier vooral een praktische discussie over het meten van contactweerstanden mogelijk is.
Daarnaast is door het AZO verhaal als het goed is helemaal duidelijk /waarom/ ik contactweerstanden wilde meten.

Naast dat de twee delen eigenlijk als losstaande verslagen worden opgebouwd worden er nog wel een (wat kortere) omvattende introductie en conclusie geschreven.

Als laatst een (oncomplete) lijst van vragen die ik wil beantwoorden.
Ik hoop een beetje een duidelijke Q&A draad te kunnen trekken door het verslag, vooral gezien ervaring leert dat ik nog wel eens begin bij een veel te specifiek onderwerp zonder de high-level vragen in zicht te houden.

* Skelet AZO
** Introductie
We willen efficiënte zonnecellen!
AZO heeft bepaalde goede eigenschappen.
AZO kan gedeponeerd worden met ALD.
Ook voor ALD: AZO is prima (tot zover bekend)
Dus we gaan kijken of de andere eigenschappen van ALD AZO ook goed zijn.
** Theorie
*** Hoe werkt een zonnecel?
Welke eigenschappen zijn uberhaupt interessant?
En waarom?
*** Wat is ALD eigenlijk?
Aan welke knoppen kunnen we draaien?
*** Valt er verder nog iets zinnigs te doen met de gelegde lagen?
Jazeker, annealing (met capping).
** Experimenten: methods
*** Sample preparatie
**** Praktisch: welk ALD proces
**** Annealing
*** Meetmethodes
**** Optisch
Uitleg VASE en IR-SE
**** Elektrisch
***** Hall
***** FPP
***** Contactweerstand
Ga hier ook in op Ag evap
** Resultaten
*** Optisch
*** Elektrisch
** Discussie
*** Optisch
Te hoge doping zorgt voor meer absorptie, maar overall transparant genoeg [citation needed]
*** Elektrisch
Trends zichtbaar, overall prima waardes haalbaar
*** Optisch + elektrisch
Tradeoff weerstand en transparantie
** Conclusie
Contactweerstanden zijn prima!
* Skelet rho
** Introductie
We willen contactweerstanden meten!
Bovenstaande is zinnig wanneer AZO verhaal eerst is verteld...
Anders: waarom rho_c meten?
Welke andere methodes zijn er?
Waarom doe ik iets anders?
** Theorie
*** Wat is contactweerstand?
*** Waarvan kunnen contactweerstanden afhangen?
Vrij algemeen, intro zonnecelfysica helpt hier al...
*** Hoe worden ze normaal gemeten?
**** Top-down
Waarom werkt dit hier niet? (de naieve manier)
**** Cox-Strack
**** Cross Bridge Kelvin Resistor
Generalisatie, verschillende gerelateerde geometrieën.
**** Of iets nieuws: toch wel top-down?
*** Meer diepgang: top-down
Waarom werkt naieve top-down soms wel, soms niet?
Balans in-plane transport vs through-plane transport -> Transfer length/Damkohler getal
Dimensieloos, wat betekent dit in het algemeen? -> Da klein -> goede spreiding
Analyse goed uitwerken, hoe ligt vergelijking met CBKR?
Goede meting oppervlakte nodig!
*** Welke design lessen vallen te leren uit theorie?
** Experimentele methods
*** Four point probing met Keithley
*** PCB vorm, waarom zo?
*** Zilver voor contact
Hoe aangebracht?
*** Image analysis
Korte bespreking, uitgebreide code mag in een appendix (of gewoon github link)
*** Per sample: varieer
- Sample size
- Geometrie (dus ook alternatieve probings met aluminiumfolie)
*** Verificatie met CBKR
Hoe uitgevoerd?
** Resultaten
Zet op een rijtje
Niet alleen samples, ook sanity checks
** Discussie
Sanity checks zijn gedaan, gingen goed!
Samples geven hier en daar wat spreiding, maar wel zelfde order of magnitude
Kruisverificatie met CBKR gaat /wel/ goed!
Wat zijn de limitaties?
- Alleen bovengrens op rho_c, maar hoe dichtbij echte waarde?
- Helaas niet goed omgegaan met edge depo, stukje "waferboekhouding" aangeraden voor volgend werk
- Geen referentiesample kunnen vinden
- Flinke afwijkingen tussen Ag samples en no-Ag samples, waarom?
** Conclusie
Werkt best prima!
We hebben nu een systeem om makkelijk contactweerstanden te meten.
** Recommendations
O.a. Kruisverificatie met C&S reference sample
* Questions :questions:
** TODO Wat is de context van mijn werk?
Energietransitie!
** TODO Wat is de "holy grail"?
Efficiente zonnecellen!
** TODO Wat heb ik gedaan?
Nieuwe materialen onderzocht voor betere zonnecellen!
** TODO Welk materiaal dan?
AZO!
** TODO Waarom AZO?
Recent onderzocht als TCO, eigenschappen zijn "promising"!
*** TODO Wat is een TCO?
** TODO Welke eigenschappen dan?
Nuttige eigenschappen:
- Optisch: lage absorptie!
- Elektrisch: lage bulk resistivity!
** TODO Wat maakt deze eigenschappen belangrijk?
Overzichtje efficientie zonnecellen
** TODO Welke parameters kunnen we controleren?
